apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: secret-volume
              mountPath: /etc/nginx/secret
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: nginx-config
        - name: secret-volume
          secret:
            secretName: nginx-secret
            
